# Generated by Django 5.1.3 on 2024-11-14 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_inmueble_dueño'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='dueño',
            field=models.ForeignKey(limit_choices_to={'tipo_usuario': 'arrendador'}, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
