# Generated by Django 5.1.3 on 2024-11-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0005_region_comunas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comunas',
            new_name='Comuna',
        ),
    ]
