# Generated by Django 5.1.3 on 2024-11-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0008_alter_inmueble_comuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.comuna'),
        ),
    ]
