# Generated by Django 5.1.3 on 2024-11-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0009_alter_inmueble_comuna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ['nombre']},
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('foto', models.ImageField(upload_to='inmuebles/')),
                ('inmuebles', models.ManyToManyField(related_name='fotos', to='gestion_inmuebles.inmueble')),
            ],
        ),
    ]
