# Generated by Django 5.1.3 on 2024-11-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0010_alter_comuna_options_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='inmuebles',
            new_name='inmueble',
        ),
    ]
